### ISSUE TITLE
Add an option to update chef runlist of an existing automation

### ISSUE THREAD

**Issue by BerndKue** [sapcc/lyra-cli#3]
There is a command to update the attributes of a chef automation:
`lyra automation update chef attributes [flags]`
But I'm missing a command to update the runlist like e.g.
`lyra automation update chef runlist [flags]`

Or did I miss something in the command line help to is already providing such a feature.

Currently I work around this by deleting the automation and recreating it providing the updated runlist. But it is not very nice because I also lose the history of it.

Best Regards
Bernd

**Comment by anish3007** [comment]
In our project we need to update chef runlist before running an automation on a particular node. For this reason we shifted to using lyra cli instead of using the Converged Cloud automation dashboard. But here also we could not find a straight forward way to update automation runlist.

It would be immensely help us if we could have a command to update the runlist of an automation as stated above by @BerndKue 

Thanks,
Anish

**Comment by ArtieReus** [comment]
I will have a look and keep you posted ASAP :)

**Comment by anish3007** [comment]
Thanks @ArtieReus for your help.
